export const ADD_DIVE = "ADD_DIVE";
export const EDIT_DIVE = "EDIT_DIVE";
export const DELETE_DIVE = "DELETE_DIVE";
export const USER_FETCH_DATA_ASYNC = "USER_FETCH_DATA_ASYNC";
export const USER_FETCH_DATA = "USER_FETCH_DATA";
export const USER_FETCH_DATA_SUCCESS = "USER_FETCH_DATA_SUCCESS";
export const USER_SAVE_DATA_SUCCESS = "USER_SAVE_DATA_SUCCESS";
